package com.nic.paymentgateway;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Merchent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("MerchantId")
	private java.lang.String merchantId;
	@org.kie.api.definition.type.Label("MerchantCountry")
	private java.lang.String merchantCountry;
	@org.kie.api.definition.type.Label("MerchantCurrency")
	private java.lang.String merchantCurrency;

	@org.kie.api.definition.type.Label("FailURL")
	private java.lang.String failURL;

	@org.kie.api.definition.type.Label("AggregatorId")
	private java.lang.String aggregatorId;

	@org.kie.api.definition.type.Label("MerchantOrderNo")
	private java.lang.String merchantOrderNo;

	@org.kie.api.definition.type.Label("MerchantCustomerID")
	private java.lang.String merchantCustomerID;

	@org.kie.api.definition.type.Label("Accesmedium")
	private java.lang.String accesmedium;

	@org.kie.api.definition.type.Label("TransactionSource")
	private java.lang.String transactionSource;

	@org.kie.api.definition.type.Label("Paymode")
	private java.lang.String paymode;

	@org.kie.api.definition.type.Label("SuccessURL")
	private java.lang.String successURL;

	@org.kie.api.definition.type.Label("OtherDetails")
	private java.lang.String otherDetails;

	@org.kie.api.definition.type.Label("PostingAmount")
	private java.lang.Integer postingAmount;

	@org.kie.api.definition.type.Label("OperatingMode")
	private java.lang.String operatingMode;

	@org.kie.api.definition.type.Label("ReqParam")
	private java.lang.String reqParam;

	@org.kie.api.definition.type.Label("Statecode")
	private java.lang.String statecode;

	@org.kie.api.definition.type.Label("Gateway")
	private java.lang.String gateway;

	@org.kie.api.definition.type.Label("Merchentcode")
	private java.lang.String merchentcode;

	@org.kie.api.definition.type.Label("Transactionno")
	private java.lang.String transactionno;

	@org.kie.api.definition.type.Label("PartyName")
	private java.lang.String partyName;

	@org.kie.api.definition.type.Label("PartyAddress")
	private java.lang.String partyAddress;

	@org.kie.api.definition.type.Label("PartyPin")
	private java.lang.String partyPin;

	@org.kie.api.definition.type.Label("PartyRef")
	private java.lang.String partyRef;

	@org.kie.api.definition.type.Label("Amount1")
	private Integer amount1;

	@org.kie.api.definition.type.Label("Amount2")
	private Integer amount2;

	@org.kie.api.definition.type.Label("MobileNo")
	private java.lang.String mobileNo;

	@org.kie.api.definition.type.Label(value = "Applno")
	private java.lang.String applno;

	public Merchent() {
	}

	public java.lang.String getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(java.lang.String merchantId) {
		this.merchantId = merchantId;
	}

	public java.lang.String getMerchantCountry() {
		return this.merchantCountry;
	}

	public void setMerchantCountry(java.lang.String merchantCountry) {
		this.merchantCountry = merchantCountry;
	}

	public java.lang.String getMerchantCurrency() {
		return this.merchantCurrency;
	}

	public void setMerchantCurrency(java.lang.String merchantCurrency) {
		this.merchantCurrency = merchantCurrency;
	}

	public java.lang.String getFailURL() {
		return this.failURL;
	}

	public void setFailURL(java.lang.String failURL) {
		this.failURL = failURL;
	}

	public java.lang.String getAggregatorId() {
		return this.aggregatorId;
	}

	public void setAggregatorId(java.lang.String aggregatorId) {
		this.aggregatorId = aggregatorId;
	}

	public java.lang.String getMerchantOrderNo() {
		return this.merchantOrderNo;
	}

	public void setMerchantOrderNo(java.lang.String merchantOrderNo) {
		this.merchantOrderNo = merchantOrderNo;
	}

	public java.lang.String getMerchantCustomerID() {
		return this.merchantCustomerID;
	}

	public void setMerchantCustomerID(java.lang.String merchantCustomerID) {
		this.merchantCustomerID = merchantCustomerID;
	}

	public java.lang.String getAccesmedium() {
		return this.accesmedium;
	}

	public void setAccesmedium(java.lang.String accesmedium) {
		this.accesmedium = accesmedium;
	}

	public java.lang.String getTransactionSource() {
		return this.transactionSource;
	}

	public void setTransactionSource(java.lang.String transactionSource) {
		this.transactionSource = transactionSource;
	}

	public java.lang.String getPaymode() {
		return this.paymode;
	}

	public void setPaymode(java.lang.String paymode) {
		this.paymode = paymode;
	}

	public java.lang.String getSuccessURL() {
		return this.successURL;
	}

	public void setSuccessURL(java.lang.String successURL) {
		this.successURL = successURL;
	}

	public java.lang.String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(java.lang.String otherDetails) {
		this.otherDetails = otherDetails;
	}

	public java.lang.Integer getPostingAmount() {
		return this.postingAmount;
	}

	public void setPostingAmount(java.lang.Integer postingAmount) {
		this.postingAmount = postingAmount;
	}

	public java.lang.String getOperatingMode() {
		return this.operatingMode;
	}

	public void setOperatingMode(java.lang.String operatingMode) {
		this.operatingMode = operatingMode;
	}

	public java.lang.String getReqParam() {
		return this.reqParam;
	}

	public void setReqParam(java.lang.String reqParam) {
		this.reqParam = reqParam;
	}

	public java.lang.String getStatecode() {
		return this.statecode;
	}

	public void setStatecode(java.lang.String statecode) {
		this.statecode = statecode;
	}

	public java.lang.String getGateway() {
		return this.gateway;
	}

	public void setGateway(java.lang.String gateway) {
		this.gateway = gateway;
	}

	public java.lang.String getMerchentcode() {
		return this.merchentcode;
	}

	public void setMerchentcode(java.lang.String merchentcode) {
		this.merchentcode = merchentcode;
	}

	public java.lang.String getTransactionno() {
		return this.transactionno;
	}

	public void setTransactionno(java.lang.String transactionno) {
		this.transactionno = transactionno;
	}

	public java.lang.String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(java.lang.String partyName) {
		this.partyName = partyName;
	}

	public java.lang.String getPartyAddress() {
		return this.partyAddress;
	}

	public void setPartyAddress(java.lang.String partyAddress) {
		this.partyAddress = partyAddress;
	}

	public java.lang.String getPartyPin() {
		return this.partyPin;
	}

	public void setPartyPin(java.lang.String partyPin) {
		this.partyPin = partyPin;
	}

	public java.lang.String getPartyRef() {
		return this.partyRef;
	}

	public void setPartyRef(java.lang.String partyRef) {
		this.partyRef = partyRef;
	}

	public java.lang.String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(java.lang.String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public java.lang.Integer getAmount1() {
		return this.amount1;
	}

	public void setAmount1(java.lang.Integer amount1) {
		this.amount1 = amount1;
	}

	public java.lang.Integer getAmount2() {
		return this.amount2;
	}

	public void setAmount2(java.lang.Integer amount2) {
		this.amount2 = amount2;
	}

	public java.lang.String getApplno() {
		return this.applno;
	}

	public void setApplno(java.lang.String applno) {
		this.applno = applno;
	}

	public Merchent(java.lang.String merchantId,
			java.lang.String merchantCountry,
			java.lang.String merchantCurrency, java.lang.String failURL,
			java.lang.String aggregatorId, java.lang.String merchantOrderNo,
			java.lang.String merchantCustomerID, java.lang.String accesmedium,
			java.lang.String transactionSource, java.lang.String paymode,
			java.lang.String successURL, java.lang.String otherDetails,
			java.lang.Integer postingAmount, java.lang.String operatingMode,
			java.lang.String reqParam, java.lang.String statecode,
			java.lang.String gateway, java.lang.String merchentcode,
			java.lang.String transactionno, java.lang.String partyName,
			java.lang.String partyAddress, java.lang.String partyPin,
			java.lang.String partyRef, java.lang.Integer amount1,
			java.lang.Integer amount2, java.lang.String mobileNo,
			java.lang.String applno) {
		this.merchantId = merchantId;
		this.merchantCountry = merchantCountry;
		this.merchantCurrency = merchantCurrency;
		this.failURL = failURL;
		this.aggregatorId = aggregatorId;
		this.merchantOrderNo = merchantOrderNo;
		this.merchantCustomerID = merchantCustomerID;
		this.accesmedium = accesmedium;
		this.transactionSource = transactionSource;
		this.paymode = paymode;
		this.successURL = successURL;
		this.otherDetails = otherDetails;
		this.postingAmount = postingAmount;
		this.operatingMode = operatingMode;
		this.reqParam = reqParam;
		this.statecode = statecode;
		this.gateway = gateway;
		this.merchentcode = merchentcode;
		this.transactionno = transactionno;
		this.partyName = partyName;
		this.partyAddress = partyAddress;
		this.partyPin = partyPin;
		this.partyRef = partyRef;
		this.amount1 = amount1;
		this.amount2 = amount2;
		this.mobileNo = mobileNo;
		this.applno = applno;
	}

}