package com.nic.paymentgateway;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Userdata implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("MobileNo")
	private java.lang.String mobileNo;
	@org.kie.api.definition.type.Label("ChallanCount")
	private java.lang.Integer challanCount;
	@org.kie.api.definition.type.Label("Demand")
	private java.lang.Integer demand;
	@org.kie.api.definition.type.Label("Head1")
	private String head1;
	@org.kie.api.definition.type.Label("Amount1")
	private java.lang.String amount1;
	@org.kie.api.definition.type.Label("Head2")
	private String head2;
	@org.kie.api.definition.type.Label("Amount2")
	private java.lang.String amount2;
	@org.kie.api.definition.type.Label("TotalAmt")
	private java.lang.String totalAmt;
	@org.kie.api.definition.type.Label("IPAddress")
	private java.lang.String IPAddress;
	@org.kie.api.definition.type.Label("PartyName")
	private java.lang.String partyName;
	@org.kie.api.definition.type.Label("PartyAddress")
	private java.lang.String partyAddress;
	@org.kie.api.definition.type.Label("PartyPin")
	private java.lang.String partyPin;
	@org.kie.api.definition.type.Label("PartyRef")
	private java.lang.String partyRef;
	@org.kie.api.definition.type.Label("ReqString")
	private java.lang.String reqString;

	@org.kie.api.definition.type.Label("Gateway")
	private java.lang.String gateway;

	@org.kie.api.definition.type.Label("Merchentcode")
	private java.lang.String merchentcode;

	@org.kie.api.definition.type.Label("Statecode")
	private java.lang.String statecode;

	@org.kie.api.definition.type.Label("Transactionno")
	private java.lang.String transactionno;

	public Userdata() {
	}

	public java.lang.String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(java.lang.String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public java.lang.Integer getChallanCount() {
		return this.challanCount;
	}

	public void setChallanCount(java.lang.Integer challanCount) {
		this.challanCount = challanCount;
	}

	public java.lang.Integer getDemand() {
		return this.demand;
	}

	public void setDemand(java.lang.Integer demand) {
		this.demand = demand;
	}

	public java.lang.String getAmount1() {
		return this.amount1;
	}

	public void setAmount1(java.lang.String amount1) {
		this.amount1 = amount1;
	}

	public java.lang.String getAmount2() {
		return this.amount2;
	}

	public void setAmount2(java.lang.String amount2) {
		this.amount2 = amount2;
	}

	public java.lang.String getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(java.lang.String totalAmt) {
		this.totalAmt = totalAmt;
	}

	public java.lang.String getIPAddress() {
		return this.IPAddress;
	}

	public void setIPAddress(java.lang.String IPAddress) {
		this.IPAddress = IPAddress;
	}

	public java.lang.String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(java.lang.String partyName) {
		this.partyName = partyName;
	}

	public java.lang.String getPartyAddress() {
		return this.partyAddress;
	}

	public void setPartyAddress(java.lang.String partyAddress) {
		this.partyAddress = partyAddress;
	}

	public java.lang.String getPartyPin() {
		return this.partyPin;
	}

	public void setPartyPin(java.lang.String partyPin) {
		this.partyPin = partyPin;
	}

	public java.lang.String getPartyRef() {
		return this.partyRef;
	}

	public void setPartyRef(java.lang.String partyRef) {
		this.partyRef = partyRef;
	}

	public java.lang.String getReqString() {
		return this.reqString;
	}

	public void setReqString(java.lang.String reqString) {
		this.reqString = reqString;
	}

	public java.lang.String getHead1() {
		return this.head1;
	}

	public void setHead1(java.lang.String head1) {
		this.head1 = head1;
	}

	public java.lang.String getHead2() {
		return this.head2;
	}

	public void setHead2(java.lang.String head2) {
		this.head2 = head2;
	}

	public java.lang.String getGateway() {
		return this.gateway;
	}

	public void setGateway(java.lang.String gateway) {
		this.gateway = gateway;
	}

	public java.lang.String getMerchentcode() {
		return this.merchentcode;
	}

	public void setMerchentcode(java.lang.String merchentcode) {
		this.merchentcode = merchentcode;
	}

	public java.lang.String getStatecode() {
		return this.statecode;
	}

	public void setStatecode(java.lang.String statecode) {
		this.statecode = statecode;
	}

	public java.lang.String getTransactionno() {
		return this.transactionno;
	}

	public void setTransactionno(java.lang.String transactionno) {
		this.transactionno = transactionno;
	}

	public Userdata(java.lang.String mobileNo, java.lang.Integer challanCount,
			java.lang.Integer demand, java.lang.String head1,
			java.lang.String amount1, java.lang.String head2,
			java.lang.String amount2, java.lang.String totalAmt,
			java.lang.String IPAddress, java.lang.String partyName,
			java.lang.String partyAddress, java.lang.String partyPin,
			java.lang.String partyRef, java.lang.String reqString,
			java.lang.String gateway, java.lang.String merchentcode,
			java.lang.String statecode, java.lang.String transactionno) {
		this.mobileNo = mobileNo;
		this.challanCount = challanCount;
		this.demand = demand;
		this.head1 = head1;
		this.amount1 = amount1;
		this.head2 = head2;
		this.amount2 = amount2;
		this.totalAmt = totalAmt;
		this.IPAddress = IPAddress;
		this.partyName = partyName;
		this.partyAddress = partyAddress;
		this.partyPin = partyPin;
		this.partyRef = partyRef;
		this.reqString = reqString;
		this.gateway = gateway;
		this.merchentcode = merchentcode;
		this.statecode = statecode;
		this.transactionno = transactionno;
	}

}